apiVersion: 1
datasources:
  - name: MySQL
    type: mysql
    url: mysql:3306
    database: hive_results
    user: root
    secureJsonData:
      password: root
    jsonData:
      tlsSkipVerify: true
